import fs from "node:fs/promises";
import path from "node:path";
import * as esbuild from "esbuild";

const repoRoot = path.resolve(new URL("..", import.meta.url).pathname);
const entryPath = path.join(repoRoot, "src/ui/index.jsx");
const bundlePath = path.join(repoRoot, "public/main.js");
const outputPath = path.join(repoRoot, "public/index.html");
const checkOnly = process.argv.includes("--check");

function renderDocument() {
  return `<!doctype html>
<html lang="zh-CN" data-theme="simple">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, interactive-widget=resizes-content" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="apple-mobile-web-app-title" content="Codex" />
    <title>Codex Remote</title>
    <link rel="icon" type="image/svg+xml" href="favicon.svg" />
    <link rel="icon" type="image/png" sizes="192x192" href="icon-192.png" />
    <link rel="apple-touch-icon" href="apple-touch-icon.png" />
    <link rel="manifest" href="site.webmanifest" />
    <meta name="theme-color" content="#15151a" />
    <link rel="stylesheet" href="/style.css" />
    <script>
      try {
        var t = localStorage.getItem("codexPhoneTheme");
        if (t) document.documentElement.dataset.theme = t;
      } catch (e) {}
    </script>
  </head>
  <body class="hide-artifacts">
    <!-- Generated by scripts/build-ui.mjs from src/ui. Edit the React source, not this file. -->
    <div id="root"></div>
    <script src="/main.js"></script>
    <script>
      if ("serviceWorker" in navigator) {
        addEventListener("load", () => navigator.serviceWorker.register("/sw.js", { scope: "/" }).catch(() => {}));
      }
    </script>
  </body>
</html>
`;
}

await esbuild.build({
  entryPoints: [entryPath],
  bundle: true,
  format: "iife",
  target: ["es2020"],
  outfile: bundlePath,
  jsx: "automatic",
  loader: { ".jsx": "jsx" },
  define: { "process.env.NODE_ENV": '"production"' },
  minify: true,
  legalComments: "none",
  logLevel: "warning",
});

const html = renderDocument();
if (checkOnly) {
  const current = await fs.readFile(outputPath, "utf8");
  if (current !== html) {
    console.error("public/index.html is out of date. Run npm run build:ui.");
    process.exit(1);
  }
  console.log("UI bundle built and index.html is current.");
} else {
  await fs.writeFile(outputPath, html, "utf8");
  console.log(`Bundled src/ui -> ${path.relative(repoRoot, bundlePath)} and generated ${path.relative(repoRoot, outputPath)}`);
}
